services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=testdb;Username=postgres;Password=yourpassword
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - testplatform_pgdata:/var/lib/postgresql/data

volumes:
  testplatform_pgdata:
